const Special = [
    {
        name: 'Desert Operations Gift Pack Key Giveaway',
        img: 'https://www.freetogame.com/offers/1/desert.jpg',
        descp: 'FreeToGame and Gamigo are working together to bring YOU a free Gift Pack with several in-game items for Desert Operations! Get your key now while supplies last!',
        amount: 120,
        amountLeft: 65,
        about: 'Strategy starts early in Game of Thrones Winter is Coming as players need to build an impenetrable base, train an army and recruit followers from a pool of iconic characters of the tv series.',
        detail: [
            '10.000 Diamonds',
            '2 Headquarter Levels',
            '10.000 Gold',
            '10.000 Oil',
            '10.000 Ammunitions',
            '10.000 Kerosene',
            '20.000.000 Dollars',
            '10.000 Diesel',
        ],
        use: [
            'Log in and click the button to unlock your key.',
            `Create your account here if you don't have a Desert Operations account already.`,
            `Start the game, click on the gift box (Top left corner, center icon) and paste the code.`,
        ],
        expiry: '*Please note these Keys expire on 01.11.2022.',
        price: 0,
    },
    {
        name: 'Game of Thrones Winter is Coming Gift Pack Key Giveaway',
        img: 'https://www.freetogame.com/offers/1/got.jpg',
        descp: 'FreeToGame and Gamigo are working together to bring YOU a free Gift Pack with several in-game items for Desert Operations! Get your key now while supplies last!',
        amount: 120,
        amountLeft: 92,
        about: 'Strategy starts early in Game of Thrones Winter is Coming as players need to build an impenetrable base, train an army and recruit followers from a pool of iconic characters of the tv series.',
        detail: [
            'Reset Talent*2',
            '30 mins Speed Up*3',
            '30 mins Speed Up (Training)*3',
            '30 mins Speed Up (Research)*3',
        ],
        use: [
            'Log in and click the button to unlock your key.',
            `Create your account here if you don't have a Desert Operations account already.`,
            `Start the game, click on the gift box (Top left corner, center icon) and paste the code.`,
        ],
        expiry: '*Please note these Keys expire on 01.11.2022.',
        price: 0,
    },
    {
        name: 'Game of Thrones Winter is Coming Gift Pack Key Giveaway',
        img: 'https://www.freetogame.com/offers/1/got.jpg',
        descp: 'FreeToGame and Gamigo are working together to bring YOU a free Gift Pack with several in-game items for Desert Operations! Get your key now while supplies last!',
        amount: 120,
        amountLeft: 0,
        about: 'Strategy starts early in Game of Thrones Winter is Coming as players need to build an impenetrable base, train an army and recruit followers from a pool of iconic characters of the tv series.',
        detail: [
            'Reset Talent*2',
            '30 mins Speed Up*3',
            '30 mins Speed Up (Training)*3',
            '30 mins Speed Up (Research)*3',
        ],
        use: [
            'Log in and click the button to unlock your key.',
            `Create your account here if you don't have a Desert Operations account already.`,
            `Start the game, click on the gift box (Top left corner, center icon) and paste the code.`,
        ],
        expiry: '*Please note these Keys expire on 01.11.2022.',
        price: 0,
    },
    {
        name: 'Game of Thrones Winter is Coming Gift Pack Key Giveaway',
        img: 'https://www.freetogame.com/offers/1/got.jpg',
        descp: 'FreeToGame and Gamigo are working together to bring YOU a free Gift Pack with several in-game items for Desert Operations! Get your key now while supplies last!',
        amount: 120,
        amountLeft: 120,
        about: 'Strategy starts early in Game of Thrones Winter is Coming as players need to build an impenetrable base, train an army and recruit followers from a pool of iconic characters of the tv series.',
        detail: [
            'Reset Talent*2',
            '30 mins Speed Up*3',
            '30 mins Speed Up (Training)*3',
            '30 mins Speed Up (Research)*3',
        ],
        use: [
            'Log in and click the button to unlock your key.',
            `Create your account here if you don't have a Desert Operations account already.`,
            `Start the game, click on the gift box (Top left corner, center icon) and paste the code.`,
        ],
        expiry: '*Please note these Keys expire on 01.11.2022.',
        price: 0,
    },
    {
        name: 'Game of Thrones Winter is Coming Gift Pack Key Giveaway',
        img: 'https://www.freetogame.com/offers/1/got.jpg',
        descp: 'FreeToGame and Gamigo are working together to bring YOU a free Gift Pack with several in-game items for Desert Operations! Get your key now while supplies last!',
        amount: 120,
        amountLeft: 0,
        about: 'Strategy starts early in Game of Thrones Winter is Coming as players need to build an impenetrable base, train an army and recruit followers from a pool of iconic characters of the tv series.',
        detail: [
            'Reset Talent*2',
            '30 mins Speed Up*3',
            '30 mins Speed Up (Training)*3',
            '30 mins Speed Up (Research)*3',
        ],
        use: [
            'Log in and click the button to unlock your key.',
            `Create your account here if you don't have a Desert Operations account already.`,
            `Start the game, click on the gift box (Top left corner, center icon) and paste the code.`,
        ],
        expiry: '*Please note these Keys expire on 01.11.2022.',
        price: 0,
    },
    {
        name: 'Game of Thrones Winter is Coming Gift Pack Key Giveaway',
        img: 'https://www.freetogame.com/offers/1/got.jpg',
        descp: 'FreeToGame and Gamigo are working together to bring YOU a free Gift Pack with several in-game items for Desert Operations! Get your key now while supplies last!',
        amount: 120,
        amountLeft: 10,
        about: 'Strategy starts early in Game of Thrones Winter is Coming as players need to build an impenetrable base, train an army and recruit followers from a pool of iconic characters of the tv series.',
        detail: [
            'Reset Talent*2',
            '30 mins Speed Up*3',
            '30 mins Speed Up (Training)*3',
            '30 mins Speed Up (Research)*3',
        ],
        use: [
            'Log in and click the button to unlock your key.',
            `Create your account here if you don't have a Desert Operations account already.`,
            `Start the game, click on the gift box (Top left corner, center icon) and paste the code.`,
        ],
        expiry: '*Please note these Keys expire on 01.11.2022.',
        price: 0,
    },
];

export default Special;
